version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: finance_db
    ports:
      - "5434:5432"
    volumes:
      # Persistencia de datos
      - postgres_data:/var/lib/postgresql/data
      # Inyección del script SQL para que se ejecute al iniciar
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: